version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: slasticarnica
      MYSQL_USER: slasticarnicauser
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: slasticarnica
      MYSQL_USER: slasticarnicauser
      MYSQL_PASSWORD: pass
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
